name: Publish Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') && github.ref == 'refs/tags/v*.*.*' && github.ref == 'refs/tags/your-branch-name'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          # python -m pip install setuptools wheel
          pip install .
      
      - name: Build Package
        run: |
          python -m pip install --upgrade build
          python -m build
      
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: |
            New release for tag ${{ github.ref }}
          generateReleaseNotes: true
          draft: false
          prerelease: false
          artifactErrorsFailBuild: true
